name: "This workflow belongs to todo App"

on:
  push:
    branches:
    - main
    
permissions:
  id-token: write
  contents: read

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: delete-task-todo-api
      IMAGE_TAG: v1
      ACR_NAME: acrak123
      ACR_LOGIN_SERVER: acrak123.azurecr.io

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Azure login
      uses: Azure/login@v2.3.0
      with:
        client-id: 7b525079-c7d5-4cd5-8737-7d191099a476
        tenant-id: 4616d612-8bc9-4839-bf28-e030beab3250
        subscription-id: 5ed71b72-e131-4c8d-8029-6d14191c6dfe

    - name: Login to ACR
      run: |
        az acr login --name $ACR_NAME
    
    - name: docker build
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - name: tag image with ACR
      run: |
        docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

    - name: push image to ACR
      run: |
        docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
        
        